language: python
python:
  - "3.7"
  
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
# command to install dependencies
install:
  - pip install -r docs/requirements.txt
  
script: pytest
