ConvertCIMovieToNWB :
  non_motion_corrected_file_name :
    keyword : ["non_corrected"]
    keyword_to_exclude : []
    extension : ["tif"]
    value : []
  xy_translation_file_name :
    keyword : ["xy"]
    keyword_to_exclude : []
    extension : ["npy","mat"]
    value : []
  motion_corrected_file_name :
    keyword : ["corrected"]
    keyword_to_exclude : ["non"]
    extension : ["tif"]
    value : []
  yaml_file_name :
    keyword : ["data"]
    keyword_to_exclude : ["default"]
    extension : ["yaml"]
    value : []
  format :
    keyword : []
    keyword_to_exclude : []
    extension : []
    value : ["external"]

ConvertSuite2PRoisToNWB:
  suite2p_dir :
    keyword : ["suite2p"]
    keyword_to_exclude : []
    extension : []
    value : []

ConvertToNWB :
  metadata_yaml :
    keyword : ["data"]
    keyword_to_exclude : []
    extension : ["yaml", "yml"]
    value : []