ConvertCiMovieToNWB :
  non_motion_corrected_file_name :
    keyword : ["non_corrected"]
    keyword_to_exclude : []
    extension : ["tif"]
    value : []
  xy_translation_file_name :
    keyword : ["xy"]
    keyword_to_exclude : []
    extension : ["npy","mat"]
    value : []
  motion_corrected_file_name :
    keyword : ["corrected"]
    keyword_to_exclude : ["non"]
    extension : ["tif", "tiff"]
    value : []
  yaml_file_name :
    keyword : ["data"]
    keyword_to_exclude : ["default"]
    extension : ["yaml"]
    value : []
  format :
    keyword : []
    keyword_to_exclude : []
    extension : []
    value : ["tiff"]
  ci_sampling_rate:
    from_other_converter: ConvertAbfToNWB
    value: ["sampling_rate_calcium_imaging"]


ConvertSuite2pRoisToNWB:
  suite2p_dir :
    keyword : ["suite2p"]
    keyword_to_exclude : []
    extension : []
    value : []

ConvertToNWB :
  metadata_yaml :
    keyword : ["data"]
    keyword_to_exclude : ["abf"]
    extension : ["yaml", "yml"]
    value : []

ConvertAbfToNWB:
  abf_yaml_file_name:
    keyword: ["abf"]
    keyword_to_exclude: []
    extension: ["yaml", "yml"]
    value: []
  abf_file_name:
    keyword: [""]
    keyword_to_exclude: []
    extension: ["abf"]
    value: []

order :
  [ConvertAbfToNWB, ConvertCiMovieToNWB, ConvertSuite2pRoisToNWB]